#!/bin/bash
# INPUT: path_to_db

# Check if the user provided the input
if [ -z "$1" ]; then
   echo "Provide a path to or a name for the database, followed by [ENTER]:"
   read path
else
   path=$1
fi

db_path=$path"/resfinder_db"
# Check if the path is valid and unexisting
if [ ! -d $path ]; then
   git clone http://compare.cbs.dtu.dk:10080/CGE/resfinder_db.git $path
else
   echo "Error: path exists! Please provide a valid and unused path..."
fi
